//------------------------------------------------------------------------------
//      Copyright (c) Microsoft Corporation.  All rights reserved.                                                                
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Terrarium.Services.Charts {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChartServiceSoap", Namespace="http://tempuri.org/")]
    public class ChartService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ChartService() {
            this.Url = "http://localhost/terrarium/charts/chartservice.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSpeciesList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSpeciesList() {
            object[] results = this.Invoke("GetSpeciesList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSpeciesList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSpeciesList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetSpeciesList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChartPopulation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChartPopulation(System.DateTime start, System.DateTime end, System.Data.DataSet included) {
            object[] results = this.Invoke("ChartPopulation", new object[] {
                        start,
                        end,
                        included});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChartPopulation(System.DateTime start, System.DateTime end, System.Data.DataSet included, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChartPopulation", new object[] {
                        start,
                        end,
                        included}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChartPopulation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChartVitals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChartVitals(System.DateTime start, System.DateTime end, string species) {
            object[] results = this.Invoke("ChartVitals", new object[] {
                        start,
                        end,
                        species});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChartVitals(System.DateTime start, System.DateTime end, string species, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChartVitals", new object[] {
                        start,
                        end,
                        species}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChartVitals(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabLatestSpeciesData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GrabLatestSpeciesData(string species) {
            object[] results = this.Invoke("GrabLatestSpeciesData", new object[] {
                        species});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGrabLatestSpeciesData(string species, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GrabLatestSpeciesData", new object[] {
                        species}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGrabLatestSpeciesData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTopAnimals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTopAnimals(string version, OrganismType tat, int num) {
            object[] results = this.Invoke("GetTopAnimals", new object[] {
                        version,
                        tat,
                        num});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTopAnimals(string version, OrganismType tat, int num, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTopAnimals", new object[] {
                        version,
                        tat,
                        num}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetTopAnimals(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum OrganismType {
        
        /// <remarks/>
        Carnivore,
        
        /// <remarks/>
        Herbivore,
        
        /// <remarks/>
        Plant,
    }
}
