//------------------------------------------------------------------------------
//      Copyright (c) Microsoft Corporation.  All rights reserved.
//------------------------------------------------------------------------------

namespace Terrarium.Forms
{
	using System;
	using System.Windows.Forms;
	using System.Drawing;
	using System.Drawing.Drawing2D;
	using System.ComponentModel;
	using System.ComponentModel.Design;
	using System.Drawing.Design;

	using Terrarium.Metal;

	/// <summary>
	/// 
	/// </summary>
	public class BottomPanel : UserControl
	{
		private Terrarium.Metal.MetalPanel titleBar;
		private Terrarium.Metal.MetalPanel metalPanel1;
		private Terrarium.Metal.MetalPanel miniMapPanel;
		private System.Windows.Forms.PictureBox navigatePictureBox;
		private Terrarium.Metal.MetalPanel metalPanel2;

		/// <summary>
		///  The actual land size in pixels as determined by
		///  the Terrarium Game Engine
		/// </summary>
		private Size landSize;
		/// <summary>
		///  The actual size of the viewport as determined
		///  during initial form setup of the primary
		///  Terrarium gaming form.
		/// </summary>
		private Size viewPortSize;
		/// <summary>
		///  The size of the viewport scaled onto the map
		///  and navigation window.
		/// </summary>
		private Size viewPortSizeOnMap;
		/// <summary>
		///  The location of the current Terrarium viewport
		///  with respect to the entire map.  Used to map
		///  the viewport onto the mapping window.
		/// </summary>
		private Point mapLocation;
		/// <summary>
		///  A bitmap used to display a small represenation
		///  of the game area on a minimap.  This Bitmap
		///  is generated by the GraphicsEngine classes.
		/// </summary>
		private Bitmap minimap;
		/// <summary>
		///  The current game mode used to enable some features
		///  and disable others as well as set up initial tab
		///  display.
		/// </summary>
		private GameModes mode;

		private bool	expanded;

		private System.Windows.Forms.Panel controlsMasterPanel;
		private System.Windows.Forms.Panel ecosystemControlsPanel;
		private Terrarium.Metal.MetalButton reintroduceAnimalButton;
		private Terrarium.Metal.MetalButton introduceAnimalEcosystemButton;
		private System.Windows.Forms.Panel terrariumControlsPanel;
		private Terrarium.Metal.MetalButton addAnimalButton;
		private Terrarium.Metal.MetalButton introduceAnimalTerrariumButton;
		private System.Windows.Forms.ComboBox addAnimalComboBox;
		private Terrarium.Metal.MetalButton loadTerrariumButton;
		private Terrarium.Metal.MetalButton newTerrariumButton;
		private Terrarium.Metal.MetalButton joinEcosystemButton;
		private System.Windows.Forms.TextBox traceTextBox;
		private Terrarium.Metal.MetalButton expandButton;
		private System.Windows.Forms.Panel buttonsPanel;
		private Terrarium.Metal.MetalButton traceButton;
		private Terrarium.Metal.MetalButton statisticsButton;
		private Terrarium.Metal.MetalButton detailsButton;
		private Terrarium.Metal.MetalButton settingsButton;
		private Terrarium.Metal.MetalButton pauseButton;

		private Terrarium.Forms.TickerBar tickerBar;
		/// <summary>
		///  The current screen saver mode used to enable some
		///  features and disable others.
		/// </summary>
		private ScreenSaverMode screenSaverMode;

		/// <summary>
		/// Fired when the control is expanded or collapsed
		/// </summary>
		public event EventHandler ExpandedChanged;

		#region Terrarium Bottom Panel Public Control Fields
		
		/// <summary>
		/// Access to the TickerBar control
		/// </summary>
		[Browsable(false)]
		public TickerBar TickerBar
		{
			get
			{
				return this.tickerBar;
			}
		}

		/// <summary>
		///  Access to the SettingsButton
		/// </summary>
		[Browsable(false)]
		public MetalButton SettingsButton
		{
			get
			{
				return this.settingsButton;
			}
		}

		/// <summary>
		///  Access to the DetailsButton
		/// </summary>
		[Browsable(false)]
		public MetalButton DetailsButton
		{
			get
			{
				return this.detailsButton;
			}
		}
		
		/// <summary>
		///  Access to the StatisticsButton
		/// </summary>
		[Browsable(false)]
		public MetalButton StatisticsButton
		{
			get
			{
				return this.statisticsButton;
			}
		}

		/// <summary>
		///  Access to the TraceButton
		/// </summary>
		[Browsable(false)]
		public MetalButton TraceButton
		{
			get
			{
				return this.traceButton;
			}
		}

		/// <summary>
		///  Access to the AddAnimalComboBox
		/// </summary>
		[Browsable(false)]
		public ComboBox AddAnimalComboBox
		{
			get
			{
				return addAnimalComboBox;
			}
		}

		/// <summary>
		///  Access to the NavigatePictureBox
		/// </summary>
		[Browsable(false)]
		public PictureBox NavigatePictureBox
		{
			get
			{
				return navigatePictureBox;
			}
		}

		/// <summary>
		///  Access to the AddAnimalButton
		/// </summary>
		[Browsable(false)]
		public MetalButton AddAnimalButton
		{
			get
			{
				return addAnimalButton;
			}
		}

		/// <summary>
		///  Access to the IntroduceAnimalEcosystemButton
		/// </summary>
		[Browsable(false)]
		public MetalButton IntroduceAnimalEcosystemButton
		{
			get
			{
				return introduceAnimalEcosystemButton;
			}
		}

		/// <summary>
		///  Access to the IntroduceAnimalTerrariumButton
		/// </summary>
		[Browsable(false)]
		public MetalButton IntroduceAnimalTerrariumButton
		{
			get
			{
				return introduceAnimalTerrariumButton;
			}
		}

		/// <summary>
		///  Access to the JoinEcosystemButton
		/// </summary>
		[Browsable(false)]
		public MetalButton JoinEcosystemButton
		{
			get
			{
				return joinEcosystemButton;
			}
		}

		/// <summary>
		///  Access to the LoadTerrariumButton
		/// </summary>
		[Browsable(false)]
		public MetalButton LoadTerrariumButton
		{
			get
			{
				return loadTerrariumButton;
			}
		}

		/// <summary>
		///  Access to the NewTerrariumButton
		/// </summary>
		[Browsable(false)]
		public MetalButton NewTerrariumButton
		{
			get
			{
				return newTerrariumButton;
			}
		}

		/// <summary>
		///  Access to the PauseButton
		/// </summary>
		[Browsable(false)]
		public MetalButton PauseButton
		{
			get
			{
				return pauseButton;
			}
		}

		/// <summary>
		///  Access to the ReintroduceAnimalButton
		/// </summary>
		[Browsable(false)]
		public MetalButton ReintroduceAnimalButton
		{
			get
			{
				return reintroduceAnimalButton;
			}
		}

		/// <summary>
		///  Access to the PeerChannelTextBox
		/// </summary>
		[Browsable(false)]
		public TextBox PeerChannelTextBox
		{
			get
			{
				// TODO: Move to Network Settings
				return null; //peerChannelTextBox;
			}
		}

		/// <summary>
		///  Access to the TraceRichTextBox
		/// </summary>
		[Browsable(false)]
		public TextBox TraceRichTextBox
		{
			get
			{
				return traceTextBox;
			}
		}
		#endregion

		#region Game Related Properties

		/// <summary>
		/// 
		/// </summary>
		public bool Expanded
		{
			get
			{
				return this.expanded;
			}
			set
			{
				this.expanded = value;
				if ( this.expanded == true )
				{
					this.Height = 120;
					this.expandButton.Text = "-";
				}
				else
				{
					this.Height = 35;
					this.expandButton.Text = "+";
				}
				this.OnExpandedChanged( new EventArgs() );
			}
		}

		/// <summary>
		///  Current game running mode.  Used to disable features.
		/// </summary>
		public ScreenSaverMode Mode
		{
			get
			{
				return screenSaverMode;
			}
        
			set
			{
				screenSaverMode = value;
			}
		}

		/// <summary>
		///  Current game mode.  Either Terrarium or EcoSystem.
		/// </summary>
		public GameModes GameMode
		{
			get
			{
				return mode;
			}

			set
			{
				mode = value;
				if (mode == GameModes.Ecosystem)
				{
					this.ecosystemControlsPanel.Visible = true;
					this.terrariumControlsPanel.Visible = false;
				}
				else
				{
					this.terrariumControlsPanel.Visible = true;
					this.ecosystemControlsPanel.Visible = false;
				}

				// TODO: Move To Network Settings
				//peerChannelTextBox.Enabled = (mode == GameModes.Terrarium);
				pauseButton.Enabled = (mode == GameModes.Terrarium);
				addAnimalButton.Enabled = (mode == GameModes.Terrarium);
				addAnimalComboBox.Enabled = (mode == GameModes.Terrarium);
				introduceAnimalTerrariumButton.Enabled = (mode == GameModes.Terrarium);
				joinEcosystemButton.Enabled = (mode == GameModes.Terrarium);

				introduceAnimalEcosystemButton.Enabled = (mode == GameModes.Ecosystem);
				reintroduceAnimalButton.Enabled = (mode == GameModes.Ecosystem);
			}
		}

		/// <summary>
		///  Allows the setting of a bitmap image to use for the minimap
		/// </summary>
		[Browsable(false)]
		public Bitmap MiniMap 
		{
			set
			{
				minimap = value;
			}
		}

		/// <summary>
		///  Sets the size of the view port
		/// </summary>
		[Browsable(false)]
		public Size ViewPortSize
		{
			set
			{
				viewPortSize = value;
				InvalidateViewportRect();
			}
		}

		/// <summary>
		///  Sets the actual size of the land
		/// </summary>
		[Browsable(false)]
		public Size LandSize
		{
			get
			{
				return landSize;
			}
        
			set
			{
				landSize = value;
				InvalidateViewportRect();
			}
		}

		/// <summary>
		///  The current map location within the Terrarium game view
		/// </summary>
		[Browsable(false)]
		public Point MapLocation 
		{
			get
			{
				return mapLocation;
			}
        
			set
			{
				mapLocation = new Point((value.X  * this.navigatePictureBox.Width) / landSize.Width,
					(value.Y  * this.navigatePictureBox.Height) / landSize.Height);
				this.navigatePictureBox.Invalidate();
			}
		}
		#endregion

		#region Event Handlers
		private void InvalidateViewportRect()
		{
			viewPortSizeOnMap = new Size((viewPortSize.Width * this.navigatePictureBox.Width) / landSize.Width,
				(viewPortSize.Height * this.navigatePictureBox.Height) / landSize.Height);
		}

		/// <summary>
		///  Make sure we invalidate the viewport rectangle if the size of the
		///  picture box changes.  In the current implementation this won't
		///  happen, but this will help enable a skinning mode.
		/// </summary>
		/// <param name="sender">PictureBox</param>
		/// <param name="e">Empty event arguments</param>
		private void navigatePictureBox_Resize(object sender, System.EventArgs e)
		{
			InvalidateViewportRect();
		}
		  
		/// <summary>
		///  navigatePictureBox event handler that controls painting of the
		///  map onto the mini map.
		/// </summary>
		/// <param name="sender">PictureBox</param>
		/// <param name="e">Graphics context objects</param>
		private void navigatePictureBox_Paint(object sender, System.Windows.Forms.PaintEventArgs e)
		{
			if (minimap != null)
			{
				e.Graphics.DrawImage((Image)minimap, this.navigatePictureBox.ClientRectangle);
			}

			int width  = ((viewPortSizeOnMap.Width + mapLocation.X)  >= this.navigatePictureBox.Width)  ? ((this.navigatePictureBox.Width - mapLocation.X) - 1)  : viewPortSizeOnMap.Width;
			int height = ((viewPortSizeOnMap.Height + mapLocation.Y) >= this.navigatePictureBox.Height) ? ((this.navigatePictureBox.Height - mapLocation.Y) - 1) : viewPortSizeOnMap.Height;

			e.Graphics.DrawRectangle(Pens.White, mapLocation.X, mapLocation.Y, width, height);
		}

		#endregion

		/// <summary>
		/// 
		/// </summary>
		/// <param name="e"></param>
		protected override void OnResize(EventArgs e)
		{
			base.OnResize (e);

			int totalWidth = this.Width;
			int miniMapWidth = this.miniMapPanel.Width;
			int subPanelWidth = (totalWidth-miniMapWidth) / 2;
			int buttonsPanelWidth = buttonsPanel.Width;

			miniMapPanel.Left = totalWidth/2 - miniMapWidth/2;

			controlsMasterPanel.Left = subPanelWidth/2 - controlsMasterPanel.Width/2;

			traceTextBox.Left = (subPanelWidth/2 - traceTextBox.Width/2) + subPanelWidth + miniMapWidth;

			buttonsPanel.Left = 16; //totalWidth/2 - buttonsPanelWidth/2;

			tickerBar.Width = totalWidth - buttonsPanel.Width - 48;

			tickerBar.Left = buttonsPanel.Left + buttonsPanel.Width + 16;

		}

		/// <summary>
		/// 
		/// </summary>
		public BottomPanel()
		{
			InitializeComponent();

			landSize = new Size(1600,1600);
			mapLocation = new Point(0,0);

		}

		private void InitializeComponent()
		{
			System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(BottomPanel));
			this.titleBar = new Terrarium.Metal.MetalPanel();
			this.expandButton = new Terrarium.Metal.MetalButton();
			this.metalPanel1 = new Terrarium.Metal.MetalPanel();
			this.buttonsPanel = new System.Windows.Forms.Panel();
			this.traceButton = new Terrarium.Metal.MetalButton();
			this.statisticsButton = new Terrarium.Metal.MetalButton();
			this.detailsButton = new Terrarium.Metal.MetalButton();
			this.settingsButton = new Terrarium.Metal.MetalButton();
			this.tickerBar = new Terrarium.Forms.TickerBar();
			this.metalPanel2 = new Terrarium.Metal.MetalPanel();
			this.controlsMasterPanel = new System.Windows.Forms.Panel();
			this.terrariumControlsPanel = new System.Windows.Forms.Panel();
			this.pauseButton = new Terrarium.Metal.MetalButton();
			this.addAnimalButton = new Terrarium.Metal.MetalButton();
			this.introduceAnimalTerrariumButton = new Terrarium.Metal.MetalButton();
			this.addAnimalComboBox = new System.Windows.Forms.ComboBox();
			this.loadTerrariumButton = new Terrarium.Metal.MetalButton();
			this.newTerrariumButton = new Terrarium.Metal.MetalButton();
			this.joinEcosystemButton = new Terrarium.Metal.MetalButton();
			this.ecosystemControlsPanel = new System.Windows.Forms.Panel();
			this.reintroduceAnimalButton = new Terrarium.Metal.MetalButton();
			this.introduceAnimalEcosystemButton = new Terrarium.Metal.MetalButton();
			this.traceTextBox = new System.Windows.Forms.TextBox();
			this.miniMapPanel = new Terrarium.Metal.MetalPanel();
			this.navigatePictureBox = new System.Windows.Forms.PictureBox();
			this.titleBar.SuspendLayout();
			this.metalPanel1.SuspendLayout();
			this.buttonsPanel.SuspendLayout();
			this.metalPanel2.SuspendLayout();
			this.controlsMasterPanel.SuspendLayout();
			this.terrariumControlsPanel.SuspendLayout();
			this.ecosystemControlsPanel.SuspendLayout();
			this.miniMapPanel.SuspendLayout();
			this.SuspendLayout();
			// 
			// titleBar
			// 
			this.titleBar.Borders = Terrarium.Metal.MetalBorders.All;
			this.titleBar.Controls.Add(this.expandButton);
			this.titleBar.Dock = System.Windows.Forms.DockStyle.Top;
			this.titleBar.Gradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.titleBar.Gradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.titleBar.Location = new System.Drawing.Point(0, 0);
			this.titleBar.Name = "titleBar";
			this.titleBar.Size = new System.Drawing.Size(800, 12);
			this.titleBar.Sunk = false;
			this.titleBar.TabIndex = 0;
			this.titleBar.UseStyles = true;
			// 
			// expandButton
			// 
			this.expandButton.BackColor = System.Drawing.Color.Transparent;
			this.expandButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.expandButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.expandButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.expandButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.expandButton.ForeColor = System.Drawing.Color.White;
			this.expandButton.Highlight = false;
			this.expandButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.expandButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.expandButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.expandButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.expandButton.Location = new System.Drawing.Point(0, 0);
			this.expandButton.Name = "expandButton";
			this.expandButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.expandButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.expandButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.expandButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.expandButton.Size = new System.Drawing.Size(17, 12);
			this.expandButton.TabIndex = 12;
			this.expandButton.TabStop = false;
			this.expandButton.Text = "-";
			this.expandButton.Click += new System.EventHandler(this.expandButton_Click);
			// 
			// metalPanel1
			// 
			this.metalPanel1.Borders = Terrarium.Metal.MetalBorders.All;
			this.metalPanel1.Controls.Add(this.buttonsPanel);
			this.metalPanel1.Controls.Add(this.tickerBar);
			this.metalPanel1.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.metalPanel1.Gradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.metalPanel1.Gradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.metalPanel1.Location = new System.Drawing.Point(0, 192);
			this.metalPanel1.Name = "metalPanel1";
			this.metalPanel1.Size = new System.Drawing.Size(800, 24);
			this.metalPanel1.Sunk = false;
			this.metalPanel1.TabIndex = 1;
			this.metalPanel1.UseStyles = true;
			// 
			// buttonsPanel
			// 
			this.buttonsPanel.BackColor = System.Drawing.Color.Transparent;
			this.buttonsPanel.Controls.Add(this.traceButton);
			this.buttonsPanel.Controls.Add(this.statisticsButton);
			this.buttonsPanel.Controls.Add(this.detailsButton);
			this.buttonsPanel.Controls.Add(this.settingsButton);
			this.buttonsPanel.Location = new System.Drawing.Point(16, 0);
			this.buttonsPanel.Name = "buttonsPanel";
			this.buttonsPanel.Size = new System.Drawing.Size(350, 24);
			this.buttonsPanel.TabIndex = 21;
			// 
			// traceButton
			// 
			this.traceButton.BackColor = System.Drawing.Color.Transparent;
			this.traceButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.traceButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.traceButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.traceButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.traceButton.ForeColor = System.Drawing.Color.White;
			this.traceButton.Highlight = false;
			this.traceButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.traceButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.traceButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.traceButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.traceButton.Image = ((System.Drawing.Image)(resources.GetObject("traceButton.Image")));
			this.traceButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.traceButton.Location = new System.Drawing.Point(261, 0);
			this.traceButton.Name = "traceButton";
			this.traceButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.traceButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.traceButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.traceButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.traceButton.Size = new System.Drawing.Size(88, 24);
			this.traceButton.TabIndex = 11;
			this.traceButton.TabStop = false;
			this.traceButton.Text = "Trace";
			// 
			// statisticsButton
			// 
			this.statisticsButton.BackColor = System.Drawing.Color.Transparent;
			this.statisticsButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.statisticsButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.statisticsButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.statisticsButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.statisticsButton.ForeColor = System.Drawing.Color.White;
			this.statisticsButton.Highlight = false;
			this.statisticsButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.statisticsButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.statisticsButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.statisticsButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.statisticsButton.Image = ((System.Drawing.Image)(resources.GetObject("statisticsButton.Image")));
			this.statisticsButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.statisticsButton.Location = new System.Drawing.Point(174, 0);
			this.statisticsButton.Name = "statisticsButton";
			this.statisticsButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.statisticsButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.statisticsButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.statisticsButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.statisticsButton.Size = new System.Drawing.Size(88, 24);
			this.statisticsButton.TabIndex = 10;
			this.statisticsButton.TabStop = false;
			this.statisticsButton.Text = "Statistics";
			// 
			// detailsButton
			// 
			this.detailsButton.BackColor = System.Drawing.Color.Transparent;
			this.detailsButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.detailsButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.detailsButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.detailsButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.detailsButton.ForeColor = System.Drawing.Color.White;
			this.detailsButton.Highlight = false;
			this.detailsButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.detailsButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.detailsButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.detailsButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.detailsButton.Image = ((System.Drawing.Image)(resources.GetObject("detailsButton.Image")));
			this.detailsButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.detailsButton.Location = new System.Drawing.Point(87, 0);
			this.detailsButton.Name = "detailsButton";
			this.detailsButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.detailsButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.detailsButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.detailsButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.detailsButton.Size = new System.Drawing.Size(88, 24);
			this.detailsButton.TabIndex = 9;
			this.detailsButton.TabStop = false;
			this.detailsButton.Text = "Details";
			// 
			// settingsButton
			// 
			this.settingsButton.BackColor = System.Drawing.Color.Transparent;
			this.settingsButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.settingsButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.settingsButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.settingsButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.settingsButton.ForeColor = System.Drawing.Color.White;
			this.settingsButton.Highlight = false;
			this.settingsButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.settingsButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.settingsButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.settingsButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.settingsButton.Image = ((System.Drawing.Image)(resources.GetObject("settingsButton.Image")));
			this.settingsButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.settingsButton.Location = new System.Drawing.Point(0, 0);
			this.settingsButton.Name = "settingsButton";
			this.settingsButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.settingsButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.settingsButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.settingsButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.settingsButton.Size = new System.Drawing.Size(88, 24);
			this.settingsButton.TabIndex = 8;
			this.settingsButton.TabStop = false;
			this.settingsButton.Text = "Settings";
			// 
			// tickerBar
			// 
			this.tickerBar.Location = new System.Drawing.Point(384, 0);
			this.tickerBar.Name = "tickerBar";
			this.tickerBar.Size = new System.Drawing.Size(400, 24);
			this.tickerBar.TabIndex = 4;

			// 
			// metalPanel2
			// 
			this.metalPanel2.Borders = Terrarium.Metal.MetalBorders.LeftAndRight;
			this.metalPanel2.Controls.Add(this.controlsMasterPanel);
			this.metalPanel2.Controls.Add(this.traceTextBox);
			this.metalPanel2.Controls.Add(this.miniMapPanel);
			this.metalPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
			this.metalPanel2.Gradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.metalPanel2.Gradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.metalPanel2.Location = new System.Drawing.Point(0, 12);
			this.metalPanel2.Name = "metalPanel2";
			this.metalPanel2.Size = new System.Drawing.Size(800, 180);
			this.metalPanel2.Sunk = true;
			this.metalPanel2.TabIndex = 2;
			this.metalPanel2.UseStyles = true;
			// 
			// controlsMasterPanel
			// 
			this.controlsMasterPanel.BackColor = System.Drawing.Color.Transparent;
			this.controlsMasterPanel.Controls.Add(this.terrariumControlsPanel);
			this.controlsMasterPanel.Controls.Add(this.loadTerrariumButton);
			this.controlsMasterPanel.Controls.Add(this.newTerrariumButton);
			this.controlsMasterPanel.Controls.Add(this.joinEcosystemButton);
			this.controlsMasterPanel.Controls.Add(this.ecosystemControlsPanel);
			this.controlsMasterPanel.Location = new System.Drawing.Point(8, 8);
			this.controlsMasterPanel.Name = "controlsMasterPanel";
			this.controlsMasterPanel.Size = new System.Drawing.Size(344, 72);
			this.controlsMasterPanel.TabIndex = 18;
			// 
			// terrariumControlsPanel
			// 
			this.terrariumControlsPanel.BackColor = System.Drawing.Color.Transparent;
			this.terrariumControlsPanel.Controls.Add(this.pauseButton);
			this.terrariumControlsPanel.Controls.Add(this.addAnimalButton);
			this.terrariumControlsPanel.Controls.Add(this.introduceAnimalTerrariumButton);
			this.terrariumControlsPanel.Controls.Add(this.addAnimalComboBox);
			this.terrariumControlsPanel.Location = new System.Drawing.Point(8, 40);
			this.terrariumControlsPanel.Name = "terrariumControlsPanel";
			this.terrariumControlsPanel.Size = new System.Drawing.Size(328, 24);
			this.terrariumControlsPanel.TabIndex = 22;
			// 
			// pauseButton
			// 
			this.pauseButton.BackColor = System.Drawing.Color.Transparent;
			this.pauseButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.pauseButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.pauseButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.pauseButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.pauseButton.ForeColor = System.Drawing.Color.White;
			this.pauseButton.Highlight = false;
			this.pauseButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.pauseButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.pauseButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.pauseButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.pauseButton.Image = ((System.Drawing.Image)(resources.GetObject("pauseButton.Image")));
			this.pauseButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.pauseButton.Location = new System.Drawing.Point(256, 0);
			this.pauseButton.Name = "pauseButton";
			this.pauseButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.pauseButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.pauseButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.pauseButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.pauseButton.Size = new System.Drawing.Size(72, 24);
			this.pauseButton.TabIndex = 22;
			this.pauseButton.TabStop = false;
			this.pauseButton.Text = "Pause";
			// 
			// addAnimalButton
			// 
			this.addAnimalButton.BackColor = System.Drawing.Color.Transparent;
			this.addAnimalButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.addAnimalButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.addAnimalButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.addAnimalButton.Enabled = false;
			this.addAnimalButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.addAnimalButton.ForeColor = System.Drawing.Color.White;
			this.addAnimalButton.Highlight = false;
			this.addAnimalButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.addAnimalButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.addAnimalButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.addAnimalButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.addAnimalButton.Image = ((System.Drawing.Image)(resources.GetObject("addAnimalButton.Image")));
			this.addAnimalButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.addAnimalButton.Location = new System.Drawing.Point(176, 0);
			this.addAnimalButton.Name = "addAnimalButton";
			this.addAnimalButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.addAnimalButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.addAnimalButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.addAnimalButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.addAnimalButton.Size = new System.Drawing.Size(72, 24);
			this.addAnimalButton.TabIndex = 18;
			this.addAnimalButton.TabStop = false;
			this.addAnimalButton.Text = "Insert";
			// 
			// introduceAnimalTerrariumButton
			// 
			this.introduceAnimalTerrariumButton.BackColor = System.Drawing.Color.Transparent;
			this.introduceAnimalTerrariumButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.introduceAnimalTerrariumButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.introduceAnimalTerrariumButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.introduceAnimalTerrariumButton.Enabled = false;
			this.introduceAnimalTerrariumButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.introduceAnimalTerrariumButton.ForeColor = System.Drawing.Color.White;
			this.introduceAnimalTerrariumButton.Highlight = false;
			this.introduceAnimalTerrariumButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.introduceAnimalTerrariumButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.introduceAnimalTerrariumButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.introduceAnimalTerrariumButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.introduceAnimalTerrariumButton.Image = ((System.Drawing.Image)(resources.GetObject("introduceAnimalTerrariumButton.Image")));
			this.introduceAnimalTerrariumButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.introduceAnimalTerrariumButton.Location = new System.Drawing.Point(0, 0);
			this.introduceAnimalTerrariumButton.Name = "introduceAnimalTerrariumButton";
			this.introduceAnimalTerrariumButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.introduceAnimalTerrariumButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.introduceAnimalTerrariumButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.introduceAnimalTerrariumButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.introduceAnimalTerrariumButton.Size = new System.Drawing.Size(72, 24);
			this.introduceAnimalTerrariumButton.TabIndex = 17;
			this.introduceAnimalTerrariumButton.TabStop = false;
			this.introduceAnimalTerrariumButton.Text = "Add";
			// 
			// addAnimalComboBox
			// 
			this.addAnimalComboBox.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.addAnimalComboBox.Location = new System.Drawing.Point(80, 0);
			this.addAnimalComboBox.Name = "addAnimalComboBox";
			this.addAnimalComboBox.Size = new System.Drawing.Size(88, 20);
			this.addAnimalComboBox.TabIndex = 16;
			// 
			// loadTerrariumButton
			// 
			this.loadTerrariumButton.BackColor = System.Drawing.Color.Transparent;
			this.loadTerrariumButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.loadTerrariumButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.loadTerrariumButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.loadTerrariumButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.loadTerrariumButton.ForeColor = System.Drawing.Color.White;
			this.loadTerrariumButton.Highlight = false;
			this.loadTerrariumButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.loadTerrariumButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.loadTerrariumButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.loadTerrariumButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.loadTerrariumButton.Image = ((System.Drawing.Image)(resources.GetObject("loadTerrariumButton.Image")));
			this.loadTerrariumButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.loadTerrariumButton.Location = new System.Drawing.Point(232, 8);
			this.loadTerrariumButton.Name = "loadTerrariumButton";
			this.loadTerrariumButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.loadTerrariumButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.loadTerrariumButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.loadTerrariumButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.loadTerrariumButton.Size = new System.Drawing.Size(104, 24);
			this.loadTerrariumButton.TabIndex = 20;
			this.loadTerrariumButton.TabStop = false;
			this.loadTerrariumButton.Text = "Open Terrarium";
			// 
			// newTerrariumButton
			// 
			this.newTerrariumButton.BackColor = System.Drawing.Color.Transparent;
			this.newTerrariumButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.newTerrariumButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.newTerrariumButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.newTerrariumButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.newTerrariumButton.ForeColor = System.Drawing.Color.White;
			this.newTerrariumButton.Highlight = false;
			this.newTerrariumButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.newTerrariumButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.newTerrariumButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.newTerrariumButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.newTerrariumButton.Image = ((System.Drawing.Image)(resources.GetObject("newTerrariumButton.Image")));
			this.newTerrariumButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.newTerrariumButton.Location = new System.Drawing.Point(120, 8);
			this.newTerrariumButton.Name = "newTerrariumButton";
			this.newTerrariumButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.newTerrariumButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.newTerrariumButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.newTerrariumButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.newTerrariumButton.Size = new System.Drawing.Size(104, 24);
			this.newTerrariumButton.TabIndex = 19;
			this.newTerrariumButton.TabStop = false;
			this.newTerrariumButton.Text = "New Terrarium";
			// 
			// joinEcosystemButton
			// 
			this.joinEcosystemButton.BackColor = System.Drawing.Color.Transparent;
			this.joinEcosystemButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.joinEcosystemButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.joinEcosystemButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.joinEcosystemButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.joinEcosystemButton.ForeColor = System.Drawing.Color.White;
			this.joinEcosystemButton.Highlight = false;
			this.joinEcosystemButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.joinEcosystemButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.joinEcosystemButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.joinEcosystemButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.joinEcosystemButton.Image = ((System.Drawing.Image)(resources.GetObject("joinEcosystemButton.Image")));
			this.joinEcosystemButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.joinEcosystemButton.Location = new System.Drawing.Point(8, 8);
			this.joinEcosystemButton.Name = "joinEcosystemButton";
			this.joinEcosystemButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.joinEcosystemButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.joinEcosystemButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.joinEcosystemButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.joinEcosystemButton.Size = new System.Drawing.Size(104, 24);
			this.joinEcosystemButton.TabIndex = 18;
			this.joinEcosystemButton.TabStop = false;
			this.joinEcosystemButton.Text = "Join Ecosystem";
			// 
			// ecosystemControlsPanel
			// 
			this.ecosystemControlsPanel.BackColor = System.Drawing.Color.Transparent;
			this.ecosystemControlsPanel.Controls.Add(this.reintroduceAnimalButton);
			this.ecosystemControlsPanel.Controls.Add(this.introduceAnimalEcosystemButton);
			this.ecosystemControlsPanel.Location = new System.Drawing.Point(8, 40);
			this.ecosystemControlsPanel.Name = "ecosystemControlsPanel";
			this.ecosystemControlsPanel.Size = new System.Drawing.Size(328, 24);
			this.ecosystemControlsPanel.TabIndex = 23;
			// 
			// reintroduceAnimalButton
			// 
			this.reintroduceAnimalButton.BackColor = System.Drawing.Color.Transparent;
			this.reintroduceAnimalButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.reintroduceAnimalButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.reintroduceAnimalButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.reintroduceAnimalButton.Enabled = false;
			this.reintroduceAnimalButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.reintroduceAnimalButton.ForeColor = System.Drawing.Color.White;
			this.reintroduceAnimalButton.Highlight = false;
			this.reintroduceAnimalButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.reintroduceAnimalButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.reintroduceAnimalButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.reintroduceAnimalButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.reintroduceAnimalButton.Image = ((System.Drawing.Image)(resources.GetObject("reintroduceAnimalButton.Image")));
			this.reintroduceAnimalButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.reintroduceAnimalButton.Location = new System.Drawing.Point(112, 0);
			this.reintroduceAnimalButton.Name = "reintroduceAnimalButton";
			this.reintroduceAnimalButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.reintroduceAnimalButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.reintroduceAnimalButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.reintroduceAnimalButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.reintroduceAnimalButton.Size = new System.Drawing.Size(104, 24);
			this.reintroduceAnimalButton.TabIndex = 12;
			this.reintroduceAnimalButton.TabStop = false;
			this.reintroduceAnimalButton.Text = "Reintroduce";
			// 
			// introduceAnimalEcosystemButton
			// 
			this.introduceAnimalEcosystemButton.BackColor = System.Drawing.Color.Transparent;
			this.introduceAnimalEcosystemButton.Borders = Terrarium.Metal.MetalBorders.All;
			this.introduceAnimalEcosystemButton.DisabledGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.introduceAnimalEcosystemButton.DisabledGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(64)), ((System.Byte)(64)), ((System.Byte)(64)));
			this.introduceAnimalEcosystemButton.Enabled = false;
			this.introduceAnimalEcosystemButton.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.introduceAnimalEcosystemButton.ForeColor = System.Drawing.Color.White;
			this.introduceAnimalEcosystemButton.Highlight = false;
			this.introduceAnimalEcosystemButton.HighlightGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.introduceAnimalEcosystemButton.HighlightGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(192)), ((System.Byte)(192)), ((System.Byte)(192)));
			this.introduceAnimalEcosystemButton.HoverGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.introduceAnimalEcosystemButton.HoverGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.introduceAnimalEcosystemButton.Image = ((System.Drawing.Image)(resources.GetObject("introduceAnimalEcosystemButton.Image")));
			this.introduceAnimalEcosystemButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.introduceAnimalEcosystemButton.Location = new System.Drawing.Point(0, 0);
			this.introduceAnimalEcosystemButton.Name = "introduceAnimalEcosystemButton";
			this.introduceAnimalEcosystemButton.NormalGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.introduceAnimalEcosystemButton.NormalGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.introduceAnimalEcosystemButton.PressedGradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(216)), ((System.Byte)(0)));
			this.introduceAnimalEcosystemButton.PressedGradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(64)), ((System.Byte)(0)));
			this.introduceAnimalEcosystemButton.Size = new System.Drawing.Size(104, 24);
			this.introduceAnimalEcosystemButton.TabIndex = 11;
			this.introduceAnimalEcosystemButton.TabStop = false;
			this.introduceAnimalEcosystemButton.Text = "Introduce";
			// 
			// traceTextBox
			// 
			this.traceTextBox.BackColor = System.Drawing.Color.DimGray;
			this.traceTextBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.traceTextBox.Font = new System.Drawing.Font("Verdana", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.traceTextBox.ForeColor = System.Drawing.Color.White;
			this.traceTextBox.Location = new System.Drawing.Point(488, 4);
			this.traceTextBox.Multiline = true;
			this.traceTextBox.Name = "traceTextBox";
			this.traceTextBox.ReadOnly = true;
			this.traceTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
			this.traceTextBox.Size = new System.Drawing.Size(296, 76);
			this.traceTextBox.TabIndex = 2;
			this.traceTextBox.Text = "";
			// 
			// miniMapPanel
			// 
			this.miniMapPanel.Borders = Terrarium.Metal.MetalBorders.LeftAndRight;
			this.miniMapPanel.Controls.Add(this.navigatePictureBox);
			this.miniMapPanel.Gradient.Bottom = System.Drawing.Color.FromArgb(((System.Byte)(0)), ((System.Byte)(0)), ((System.Byte)(0)));
			this.miniMapPanel.Gradient.Top = System.Drawing.Color.FromArgb(((System.Byte)(96)), ((System.Byte)(96)), ((System.Byte)(96)));
			this.miniMapPanel.Location = new System.Drawing.Point(368, 0);
			this.miniMapPanel.Name = "miniMapPanel";
			this.miniMapPanel.Size = new System.Drawing.Size(88, 88);
			this.miniMapPanel.Sunk = false;
			this.miniMapPanel.TabIndex = 1;
			this.miniMapPanel.UseStyles = true;
			// 
			// navigatePictureBox
			// 
			this.navigatePictureBox.BackColor = System.Drawing.Color.Gray;
			this.navigatePictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.navigatePictureBox.Location = new System.Drawing.Point(8, 8);
			this.navigatePictureBox.Name = "navigatePictureBox";
			this.navigatePictureBox.Size = new System.Drawing.Size(70, 70);
			this.navigatePictureBox.TabIndex = 8;
			this.navigatePictureBox.TabStop = false;
			this.navigatePictureBox.Resize += new System.EventHandler(this.navigatePictureBox_Resize);
			this.navigatePictureBox.Paint += new System.Windows.Forms.PaintEventHandler(this.navigatePictureBox_Paint);
			// 
			// BottomPanel
			// 
			this.Controls.Add(this.metalPanel2);
			this.Controls.Add(this.titleBar);
			this.Controls.Add(this.metalPanel1);
			this.Name = "BottomPanel";
			this.Size = new System.Drawing.Size(800, 216);
			this.titleBar.ResumeLayout(false);
			this.metalPanel1.ResumeLayout(false);
			this.buttonsPanel.ResumeLayout(false);
			this.metalPanel2.ResumeLayout(false);
			this.controlsMasterPanel.ResumeLayout(false);
			this.terrariumControlsPanel.ResumeLayout(false);
			this.ecosystemControlsPanel.ResumeLayout(false);
			this.miniMapPanel.ResumeLayout(false);
			this.ResumeLayout(false);

		}

		private void expandButton_Click(object sender, System.EventArgs e)
		{
			this.Expanded = !this.Expanded;
		}

		/// <summary>
		/// Event implementation for the ExpandedChanged event.
		/// </summary>
		/// <param name="args"></param>
		protected virtual void OnExpandedChanged( EventArgs args )
		{
			if ( this.ExpandedChanged != null )
				this.ExpandedChanged( this, args );
		}
	}
}
