//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace Terrarium.Services.Usage {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsageServiceSoap", Namespace="http://tempuri.org/")]
    public partial class UsageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReportUsageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UsageService() {
            this.Url = global::Terrarium.Services.Properties.Settings.Default.Services_Usage_UsageService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReportUsageCompletedEventHandler ReportUsageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportUsage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReportUsage(UsageData data) {
            this.Invoke("ReportUsage", new object[] {
                        data});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReportUsage(UsageData data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReportUsage", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndReportUsage(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void ReportUsageAsync(UsageData data) {
            this.ReportUsageAsync(data, null);
        }
        
        /// <remarks/>
        public void ReportUsageAsync(UsageData data, object userState) {
            if ((this.ReportUsageOperationCompleted == null)) {
                this.ReportUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportUsageOperationCompleted);
            }
            this.InvokeAsync("ReportUsage", new object[] {
                        data}, this.ReportUsageOperationCompleted, userState);
        }
        
        private void OnReportUsageOperationCompleted(object arg) {
            if ((this.ReportUsageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportUsageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsageData {
        
        private string aliasField;
        
        private string domainField;
        
        private string gameVersionField;
        
        private string peerChannelField;
        
        private int peerCountField;
        
        private int animalCountField;
        
        private int maxAnimalCountField;
        
        private int worldWidthField;
        
        private int worldHeightField;
        
        private string machineNameField;
        
        private string oSVersionField;
        
        private int processorCountField;
        
        private string clrVersionField;
        
        private int workingSetField;
        
        private int maxWorkingSetField;
        
        private int minWorkingSetField;
        
        private int processorTimeInSecondsField;
        
        private System.DateTime processStartTimeField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        public string GameVersion {
            get {
                return this.gameVersionField;
            }
            set {
                this.gameVersionField = value;
            }
        }
        
        /// <remarks/>
        public string PeerChannel {
            get {
                return this.peerChannelField;
            }
            set {
                this.peerChannelField = value;
            }
        }
        
        /// <remarks/>
        public int PeerCount {
            get {
                return this.peerCountField;
            }
            set {
                this.peerCountField = value;
            }
        }
        
        /// <remarks/>
        public int AnimalCount {
            get {
                return this.animalCountField;
            }
            set {
                this.animalCountField = value;
            }
        }
        
        /// <remarks/>
        public int MaxAnimalCount {
            get {
                return this.maxAnimalCountField;
            }
            set {
                this.maxAnimalCountField = value;
            }
        }
        
        /// <remarks/>
        public int WorldWidth {
            get {
                return this.worldWidthField;
            }
            set {
                this.worldWidthField = value;
            }
        }
        
        /// <remarks/>
        public int WorldHeight {
            get {
                return this.worldHeightField;
            }
            set {
                this.worldHeightField = value;
            }
        }
        
        /// <remarks/>
        public string MachineName {
            get {
                return this.machineNameField;
            }
            set {
                this.machineNameField = value;
            }
        }
        
        /// <remarks/>
        public string OSVersion {
            get {
                return this.oSVersionField;
            }
            set {
                this.oSVersionField = value;
            }
        }
        
        /// <remarks/>
        public int ProcessorCount {
            get {
                return this.processorCountField;
            }
            set {
                this.processorCountField = value;
            }
        }
        
        /// <remarks/>
        public string ClrVersion {
            get {
                return this.clrVersionField;
            }
            set {
                this.clrVersionField = value;
            }
        }
        
        /// <remarks/>
        public int WorkingSet {
            get {
                return this.workingSetField;
            }
            set {
                this.workingSetField = value;
            }
        }
        
        /// <remarks/>
        public int MaxWorkingSet {
            get {
                return this.maxWorkingSetField;
            }
            set {
                this.maxWorkingSetField = value;
            }
        }
        
        /// <remarks/>
        public int MinWorkingSet {
            get {
                return this.minWorkingSetField;
            }
            set {
                this.minWorkingSetField = value;
            }
        }
        
        /// <remarks/>
        public int ProcessorTimeInSeconds {
            get {
                return this.processorTimeInSecondsField;
            }
            set {
                this.processorTimeInSecondsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProcessStartTime {
            get {
                return this.processStartTimeField;
            }
            set {
                this.processStartTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ReportUsageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591