//------------------------------------------------------------------------------
//      Copyright (c) Microsoft Corporation.  All rights reserved.                                                                
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Terrarium.Services.Reporting {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReportingServiceSoap", Namespace="http://tempuri.org/")]
    public class ReportingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ReportingService() {
            this.Url = "http://lhsdkter2/Terrarium/reporting/reportpopulation.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportPopulation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReportPopulation(System.Data.DataSet data, System.Guid guid, int currentTick) {
            object[] results = this.Invoke("ReportPopulation", new object[] {
                        data,
                        guid,
                        currentTick});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReportPopulation(System.Data.DataSet data, System.Guid guid, int currentTick, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReportPopulation", new object[] {
                        data,
                        guid,
                        currentTick}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndReportPopulation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
}
